language: python
python:
  - "2.7"
cache: pip
install:
  - pip install pep8
script:
  - pep8 --show-source --show-pep8 setup.py
  - pep8 --show-source --show-pep8 twweet-cli.py
  - python setup.py install
