language: python

python:
  - "3.5"
  - "3.6"

before_install:
  - sudo apt-get update -qq

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install codecov
  - python setup.py develop

# command to run tests and coverage
script:
  - coverage erase
  # My test files

after_success:
  - coverage combine
  - coverage report
  - codecov

sudo:
    required

dist:
    trusty
